# Generated by Django 4.2 on 2023-08-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinzApp', '0002_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markedprice',
            field=models.IntegerField(default=0),
        ),
    ]
