# Generated by Django 4.2 on 2023-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinzApp', '0006_order_customer_name_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image2',
            field=models.ImageField(default='', upload_to='uploads/products'),
        ),
    ]
